<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWPCxnk2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWPCxnk2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWPCxnk2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWPCxnk2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWPCxnk2\App_KernelDevDebugContainer([
    'container.build_hash' => 'WPCxnk2',
    'container.build_id' => '6eaef8d2',
    'container.build_time' => 1708272451,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWPCxnk2');
