<?php

namespace ContainerWPCxnk2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFreelancerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CQTeWUz.App\Entity\Freelancer' shared service.
     *
     * @return \App\Entity\Freelancer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.CQTeWUz": it needs an instance of "App\\Entity\\Freelancer" but this type has been excluded in "config/services.yaml".');
    }
}
