<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcxxQ2h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcxxQ2h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXcxxQ2h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXcxxQ2h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXcxxQ2h\App_KernelDevDebugContainer([
    'container.build_hash' => 'XcxxQ2h',
    'container.build_id' => '6afca64f',
    'container.build_time' => 1708361652,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXcxxQ2h');
