<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6VMx1Li\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6VMx1Li/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6VMx1Li.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6VMx1Li\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6VMx1Li\App_KernelDevDebugContainer([
    'container.build_hash' => '6VMx1Li',
    'container.build_id' => 'e7cdfec0',
    'container.build_time' => 1709038265,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6VMx1Li');
